### ISSUE TITLE
Docs-Maven-Plugin link in Readme.md broken

### ISSUE THREAD

**Issue by jsvogt** [OpenPOWERFoundation/Docs-Template#5]
Readme.md contains a broken link, because the Docs-Maven-Plugin project doesn't exist
>> The project which control the look and feel of the document is the Docs-Maven-Plugin project.
Should this point to OpenPOWERFoundation/Docs-Master instead?

**Comment by jjscheel** [comment]
Actually, not.  The link works for those people who have access to the private project.  I will update the README.md file to clarify.  Thanks!

**Comment by jjscheel** [comment]
Despite bad commit text (which pointed at Issue #4, not #5, this was fixed in last commit.

Please review the text for clarity and let me know your thoughts.

**Comment by jsvogt** [comment]
Thank you, that's very clear now.
